version: "3.8"
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_USER: virometer
      POSTGRES_PASSWORD: virometerPasswort1
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: 